### ISSUE TITLE
Get rid of the AWS_LOCATION var

### ISSUE THREAD

**Issue by Pomax** [Pomax/filebrowser_s3#2]
We're using AWS_LOCATION as and alias for AWS_STORAGE_ROOT - but it looks like we only use this in the template file, so we should probably just straight up use AWS_STORAGE_ROOT in `./templatetags/s3thumbnails.py` and get rid of a var.

**Comment by Pomax** [comment]
@cadecairos does that sound reasonable?

**Comment by cadecairos** [comment]
Yeah lets make the change.

**Comment by Pomax** [comment]
landed as v0.1.0
